# Generated by Django 3.1.7 on 2021-03-28 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkinginfo',
            name='isactive',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
