# Generated by Django 3.1.7 on 2021-04-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20210328_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='destination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
