# Generated by Django 3.2.6 on 2021-10-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking_Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=50, verbose_name='License Plate')),
                ('checkin_time', models.DateField(verbose_name='Check In Time')),
                ('checkout_time', models.DateField(verbose_name='Check Out Time')),
                ('time_spent', models.DurationField(verbose_name='Time Spent')),
                ('total_due', models.FloatField(verbose_name='Total Due')),
            ],
        ),
    ]
