# Generated by Django 3.2.6 on 2021-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211016_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_ticket',
            name='total_due',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Due'),
        ),
        migrations.AlterField(
            model_name='total_amount',
            name='total_due',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Due'),
        ),
    ]
