# Generated by Django 3.2.6 on 2021-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211016_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_ticket',
            name='checkout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check Out Time'),
        ),
        migrations.AlterField(
            model_name='parking_ticket',
            name='time_spent',
            field=models.DurationField(blank=True, null=True, verbose_name='Time Spent'),
        ),
        migrations.AlterField(
            model_name='parking_ticket',
            name='total_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Due'),
        ),
        migrations.AlterField(
            model_name='total_amount',
            name='total_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Due'),
        ),
    ]
