# Generated by Django 3.2.6 on 2021-10-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_auto_20211016_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_amount',
            name='tickets',
        ),
        migrations.AddField(
            model_name='total_amount',
            name='month',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='total_amount',
            name='year',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
