# Generated by Django 3.2.6 on 2021-10-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_parking_ticket_checkin_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_ticket',
            name='time_spent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Time Spent'),
        ),
    ]
